# Generated by Django 3.2 on 2022-02-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_and_A_app', '0002_auto_20220217_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
